### ISSUE TITLE
Coefficient wise product

### ISSUE THREAD

**Issue by denizonural** [hughperkins/jeigen#10]
Hello,

I am trying to use Jeigen for a project dealing with matrixes, and need to calculate the coefficient wise product of a matrix. Looking around I saw that in the natives the c++ is there as CoeffBasedProduct. I am fairly new at Java and couldn't figure out how to write/add the java version to jeigen, or if it is possible to do so. Could you help me out? Do you have experience with this product or perhaps any raw implementations? Do you know of any other libraries like jeigen that does this function?

I really admire your work, thanks for your contribution and any future help :)

Cheers,
Deniz

**Comment by hughperkins** [comment]
I googled for CoeffBasedProduct, but just found the sourcecode.  Do you have a url for the doc?  And/or can you provide a precise mathematical description of what is CoeffBasedProduct, the inputs, and the outputs, please?  (Not saying I will add it, but if I have the description in front of me, I can evaluate more clearly the effort involved in adding it)

**Comment by hughperkins** [comment]
Are you sure you dont want simply:
```
dm1 = dm1.mul( dm2 );    // by-element multiplication
```
?

**Comment by hughperkins** [comment]
Closing this, since no updates since 14 days or so.  Please feel free to re-open if still needed?
