### ISSUE TITLE
Bug: Sparse.<op>(Dense) Copy and Paste II

### ISSUE THREAD

**Issue by Langlaeufer** [hughperkins/jeigen#12]
In SparceLil.java

                public DenseMatrix **div**( DenseMatrix second ) {
                               return toDense()**.sub**(second);
                }
                public DenseMatrix **mul**( DenseMatrix second ) {
                               return toDense()**.sub**(second);
                }

**Comment by hughperkins** [comment]
adressed in 3a1b0c1

**Comment by hughperkins** [comment]
Thanks! :-)
