### ISSUE TITLE
Downloadable libraries still have non-Public DenseMatrixComplex class

### ISSUE THREAD

**Issue by AmrikSadhra** [hughperkins/jeigen#6]

**Comment by hughperkins** [comment]
Yes... please feel free to bump this once a week until I do this...

**Comment by behsaman** [comment]
please add DenseMatrixComplex Class. Thanks.

**Comment by hughperkins** [comment]
Please confirm which platform(s) you need?  I'm tempted to ditch 32-bit?  I'm pondering adding Mac OS X?

**Comment by hughperkins** [comment]
Working on this.  I've created jars for each of win32, win64, linux32, linux64.  I havent tested that the windows jars run on a fresh windows system yet.  I suspect they might need the visual studios 2010 distributables installed.  So I need to test that.

Pondering if I can get a mac build too somehow...

builds so far are here: http://hughperkins.com/download/jeigen-1.2beta

**Comment by hughperkins** [comment]
Update: added the msvc2010 redistributables to the windows jars, and uploaded these latest versions to the url above, ie http://hughperkins.com/download/jeigen-1.2beta

**Comment by hughperkins** [comment]
Added a mac build!  http://hughperkins.com/download/jeigen-1.2beta/Jeigen-mac-64.jar

**Comment by hughperkins** [comment]
Ok, in theory, you just need http://hughperkins.com/download/jeigen-1.2beta/Jeigen-onefat.jar and http://hughperkins.com/jeigen/jna-4.1.0.jar , for all the following platforms:
- linux 32
- linux 64
- win 32
- win 64
- mac os x 64

Can you test this works ok, and let me know any issues please?

**Comment by hughperkins** [comment]
Created 1.2 release https://github.com/hughperkins/jeigen/releases/tag/v1.2 , which should address this issue.

**Comment by behsaman** [comment]
Thank you very much for your response.

**Comment by hughperkins** [comment]
:-)

**Comment by hughperkins** [comment]
k.  Let me know if any issues :-)
